# For more information: https://github.com/julien-r44/adonis-sail
version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: like-mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DB_NAME:?err}'
      MYSQL_USER: '${MYSQL_USER:?err}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD?:err}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
